name: linux
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build EventBus on ubuntu
      shell: bash
      run: |
        chmod 777 build.sh sample/build.sh
        ./build.sh
        ./sample/build.sh
    - uses: actions/upload-artifact@v3
      with:
        name: EventBus
        path: ./output
